### ISSUE TITLE
SPU ASMJIT does not work on aarch64

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#12794]
Tested on aarch64 linux. LLVM works fine for both PPU and SPU.
ASMJIT crashes when compiling the SPU programs. The emulator simply aborts due to a segfault in asmjit code.

Backtrace:
```
Thread 69 "SPU Worker 3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xfffe44cfb5c0 (LWP 16007)]
0x00000000025c1fa0 in asmjit::_abi_1_9::CodeHolder::growBuffer(asmjit::_abi_1_9::CodeBuffer*, unsigned long) ()
(gdb) bt
#0  0x00000000025c1fa0 in asmjit::_abi_1_9::CodeHolder::growBuffer(asmjit::_abi_1_9::CodeBuffer*, unsigned long) ()
#1  0x00000000025c0898 in asmjit::_abi_1_9::BaseAssembler::embedDataArray(asmjit::_abi_1_9::TypeId, void const*, unsigned long, unsigned long) ()
#2  0x0000000000d916b8 in spu_recompiler::compile(spu_program&&) ()
#3  0x00000000007b7484 in spu_cache::initialize()::{lambda()#1}::operator()() const ()
#4  0x00000000007b755c in named_thread<spu_cache::initialize()::{lambda()#1}>::trampoline(void*) ()
#5  0x0000fffff4000aec in  () at /usr/lib/libc.so.6
#6  0x0000fffff406a5dc in  () at /usr/lib/libc.so.6
```

**Comment by kd-11** [comment]
SPU LLVM works now after https://github.com/RPCS3/rpcs3/commit/c572226b0d3eb8ae174beeead69c7a6756cd4454
Most games still just freeze after modules are loaded, but some like arkedo 01 go ingame.
