### ISSUE TITLE
AddressSanitizer: container-overflow in SPUCommonRecompiler.cpp

### ISSUE THREAD

**Issue by oltolm** [RPCS3/rpcs3#16043]
I get this ASAN error in latest master.

```
=================================================================
==5420==ERROR: AddressSanitizer: container-overflow on address 0x12baa6e101f0 at pc 0x000001c2edcc bp 0x00b1a77ed160 sp 0x00b1a77ed1a8
READ of size 1 at 0x12baa6e101f0 thread T253
    #0 0x1c2edcb in spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::$_3::operator()() const C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:5456:22
    #1 0x1c1e18f in spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*) C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:7053:4
    #2 0x1c74dfd in spu_cache::initialize(bool)::$_0::operator()() const C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:982:34
    #3 0x1c725c9 in named_thread<spu_cache::initialize(bool)::$_0>::entry_point2() C:/src/rpcs3/rpcs3/../Utilities/Thread.h:505:49
    #4 0x1c3d814 in named_thread<spu_cache::initialize(bool)::$_0>::entry_point(thread_base*) C:/src/rpcs3/rpcs3/../Utilities/Thread.h:472:45
    #5 0x2d036b4a  (<unknown module>)

0x12baa6e101f0 is located 624 bytes inside of 728-byte region [0x12baa6e0ff80,0x12baa6e10258)
allocated by thread T253 here:
    #0 0x7ffd6a8d4d91 in operator new(unsigned long long) (C:\msys64\clang64\bin\libclang_rt.asan_dynamic-x86_64.dll+0x180054d91)
    #1 0x40eda6 in void* std::__1::__libcpp_operator_new[abi:nn180100]<unsigned long long>(unsigned long long) C:/msys64/clang64/include/c++/v1/new:271:10  
    #2 0x40ecfe in std::__1::__libcpp_allocate[abi:nn180100](unsigned long long, unsigned long long) C:/msys64/clang64/include/c++/v1/new:295:10
    #3 0x1c4d57e in std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>::allocate[abi:nn180100](unsigned long long) C:/msys64/clang64/include/c++/v1/__memory/allocator.h:125:32
    #4 0x1c4d3eb in std::__1::__allocation_result<std::__1::allocator_traits<std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 
4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>>::pointer> std::__1::__allocate_at_least[abi:nn180100]<std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>>(std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>&, unsigned long long) C:/msys64/clang64/include/c++/v1/__memory/allocate_at_least.h:55:19
    #5 0x1c4c921 in std::__1::__split_buffer<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator, std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>&>::__split_buffer(unsigned long long, unsigned long long, std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>&) C:/msys64/clang64/include/c++/v1/__split_buffer:343:25        
    #6 0x1c49dfd in spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator* std::__1::vector<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator, std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>>::__emplace_back_slow_path<unsigned int&>(unsigned int&) C:/msys64/clang64/include/c++/v1/vector:1489:47
    #7 0x1c285f6 in spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator& std::__1::vector<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator, std::__1::allocator<spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::block_reg_state_iterator>>::emplace_back<unsigned int&>(unsigned int&) C:/msys64/clang64/include/c++/v1/vector:1511:13
    #8 0x1c10ecf in spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*) C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:4952:15
    #9 0x1c74dfd in spu_cache::initialize(bool)::$_0::operator()() const C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:982:34
    #10 0x1c725c9 in named_thread<spu_cache::initialize(bool)::$_0>::entry_point2() C:/src/rpcs3/rpcs3/../Utilities/Thread.h:505:49
    #11 0x1c3d814 in named_thread<spu_cache::initialize(bool)::$_0>::entry_point(thread_base*) C:/src/rpcs3/rpcs3/../Utilities/Thread.h:472:45
    #12 0x2d036b4a  (<unknown module>)

Thread T253 created by T178 here:
    #0 0x7ffd6a8d4536 in CreateThread (C:\msys64\clang64\bin\libclang_rt.asan_dynamic-x86_64.dll+0x180054536)
    #1 0x7ffdf9a11896  (C:\WINDOWS\System32\ucrtbase.dll+0x180021896)
    #2 0xb281e9 in thread_base::start() C:/src/rpcs3/Utilities/Thread.cpp:2112:13
    #3 0x1c721be in named_thread<spu_cache::initialize(bool)::$_0>::named_thread<spu_cache::initialize(bool)::$_0 const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, spu_cache::initialize(bool)::$_0 const&) C:/src/rpcs3/rpcs3/../Utilities/Thread.h:557:11
    #4 0x1becdb1 in named_thread_group<spu_cache::initialize(bool)::$_0>::named_thread_group(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned int, spu_cache::initialize(bool)::$_0&&) C:/src/rpcs3/rpcs3/../Utilities/Thread.h:759:44
    #5 0x1bea949 in spu_cache::initialize(bool) C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:798:21
    #6 0x1ac001c in ppu_thread::cpu_task() C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:2172:4
    #7 0xe4476f in cpu_thread::operator()() C:/src/rpcs3/rpcs3/Emu/CPU/CPUThread.cpp:657:4
    #8 0x15853fa in named_thread<ppu_thread>::entry_point2() C:/src/rpcs3/rpcs3/../Utilities/Thread.h:491:14
    #9 0x15304d6 in named_thread<ppu_thread>::entry_point(thread_base*) C:/src/rpcs3/rpcs3/../Utilities/Thread.h:472:45
    #10 0x2d03774a  (<unknown module>)

Thread T178 created by T0 here:
    #0 0x7ffd6a8d4536 in CreateThread (C:\msys64\clang64\bin\libclang_rt.asan_dynamic-x86_64.dll+0x180054536)
    #1 0x7ffdf9a11896  (C:\WINDOWS\System32\ucrtbase.dll+0x180021896)
    #2 0xb281e9 in thread_base::start() C:/src/rpcs3/Utilities/Thread.cpp:2112:13
    #3 0x15a9085 in named_thread<ppu_thread>::named_thread<ppu_thread_params&, char const (&) [12], int&, int>(ppu_thread_params&, char const (&) [12], int&, int&&) C:/src/rpcs3/rpcs3/../Utilities/Thread.h:538:11
    #4 0x15a8d47 in named_thread<ppu_thread>* std::__1::construct_at[abi:nn180100]<named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, 
int, named_thread<ppu_thread>*>(named_thread<ppu_thread>*, ppu_thread_params&, char const (&) [12], int&, int&&) C:/msys64/clang64/include/c++/v1/__memory/construct_at.h:41:46
    #5 0x15a8ceb in named_thread<ppu_thread>* std::__1::__construct_at[abi:nn180100]<named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int, named_thread<ppu_thread>*>(named_thread<ppu_thread>*, ppu_thread_params&, char const (&) [12], int&, int&&) C:/msys64/clang64/include/c++/v1/__memory/construct_at.h:49:10
    #6 0x15a8c9f in void std::__1::allocator_traits<std::__1::allocator<named_thread<ppu_thread>>>::construct[abi:nn180100]<named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int, void, void>(std::__1::allocator<named_thread<ppu_thread>>&, named_thread<ppu_thread>*, ppu_thread_params&, char const (&) [12], int&, int&&) C:/msys64/clang64/include/c++/v1/__memory/allocator_traits.h:305:5
    #7 0x15a8bcd in std::__1::__shared_ptr_emplace<named_thread<ppu_thread>, std::__1::allocator<named_thread<ppu_thread>>>::__shared_ptr_emplace[abi:nn180100]<ppu_thread_params&, char const (&) [12], int&, int, std::__1::allocator<named_thread<ppu_thread>>, 0>(std::__1::allocator<named_thread<ppu_thread>>, ppu_thread_params&, char const (&) [12], int&, int&&) C:/msys64/clang64/include/c++/v1/__memory/shared_ptr.h:265:5
    #8 0x15a88b0 in std::__1::shared_ptr<named_thread<ppu_thread>> std::__1::allocate_shared[abi:nn180100]<named_thread<ppu_thread>, std::__1::allocator<named_thread<ppu_thread>>, ppu_thread_params&, char const (&) [12], int&, int, void>(std::__1::allocator<named_thread<ppu_thread>> const&, ppu_thread_params&, 
char const (&) [12], int&, int&&) C:/msys64/clang64/include/c++/v1/__memory/shared_ptr.h:823:51
    #9 0x15a86c1 in std::__1::shared_ptr<named_thread<ppu_thread>> std::__1::make_shared[abi:nn180100]<named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int, void>(ppu_thread_params&, char const (&) [12], int&, int&&) C:/msys64/clang64/include/c++/v1/__memory/shared_ptr.h:831:10
    #10 0x15a856d in std::__1::shared_ptr<T0> idm::make_ptr<named_thread<ppu_thread>, named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int>(T1&&...)::'lambda'()::operator()() const C:/src/rpcs3/rpcs3/Emu/IdManager.h:572:51
    #11 0x15a8311 in std::__1::pair<id_manager::id_key, std::__1::shared_ptr<void>>* idm::create_id<named_thread<ppu_thread>, named_thread<ppu_thread>, std::__1::shared_ptr<T0> idm::make_ptr<named_thread<ppu_thread>, named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int>(T1&&...)::'lambda'()>(std::__1::shared_ptr<T0> idm::make_ptr<named_thread<ppu_thread>, named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int>(T1&&...)::'lambda'()&&, unsigned int) C:/src/rpcs3/rpcs3/Emu/IdManager.h:534:20
    #12 0x152e07d in std::__1::shared_ptr<T0> idm::make_ptr<named_thread<ppu_thread>, named_thread<ppu_thread>, ppu_thread_params&, char const (&) [12], int&, int>(T1&&...) C:/src/rpcs3/rpcs3/Emu/IdManager.h:572:19
    #13 0x14eee6e in ppu_load_exec(elf_object<elf_be, unsigned long long, (elf_machine)21, (elf_os)0, (elf_type)2> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, utils::serial*) C:/src/rpcs3/rpcs3/Emu/Cell/PPUModule.cpp:2611:13
    #14 0x813efa in Emulator::Load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long long) C:/src/rpcs3/rpcs3/Emu/System.cpp:2290:8
    #15 0x7feb4d in Emulator::BootGame(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, cfg_mode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) C:/src/rpcs3/rpcs3/Emu/System.cpp:933:12
    #16 0x1302f9b in main_window::Boot(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool, cfg_mode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) C:/src/rpcs3/rpcs3/rpcs3qt/main_window.cpp:542:29
    #17 0x13027bd in main_window::OnPlayOrPause() C:/src/rpcs3/rpcs3/rpcs3qt/main_window.cpp:452:4
    #18 0x11f5fbc in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (main_window::*)()>::call(void (main_window::*)(), main_window*, void**) C:/msys64/clang64/include/qt6/QtCore/qobjectdefs_impl.h:145:13
    #19 0x11f5db0 in void QtPrivate::FunctionPointer<void (main_window::*)()>::call<QtPrivate::List<>, void>(void (main_window::*)(), main_window*, void**) 
C:/msys64/clang64/include/qt6/QtCore/qobjectdefs_impl.h:182:13
    #20 0x11f5c09 in QtPrivate::QCallableObject<void (main_window::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, 
bool*) C:/msys64/clang64/include/qt6/QtCore/qobjectdefs_impl.h:553:21
    #21 0x7ffd6a3f49bb in void doActivate<false>(QObject*, int, void**) (E:\build-rpcs3-clang\bin\Qt6Core.dll+0x1800e49bb)
    #22 0x7ffd7ca0e325 in QAction::activate(QAction::ActionEvent) (E:\build-rpcs3-clang\bin\Qt6Gui.dll+0x18049e325)
    #23 0x7ffd7d97a444 in QAbstractButtonPrivate::click() (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18012a444)
    #24 0x7ffd7d97b57e in QAbstractButton::mouseReleaseEvent(QMouseEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18012b57e)
    #25 0x7ffd7da9e6a6 in QToolButton::mouseReleaseEvent(QMouseEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18024e6a6)
    #26 0x7ffd7d8ad57d in QWidget::event(QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18005d57d)
    #27 0x7ffd7da9edf8 in QToolButton::event(QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18024edf8)
    #28 0x7ffd7d858f6f in QApplicationPrivate::notify_helper(QObject*, QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x180008f6f)
    #29 0x7ffd7d85b599 in QApplication::notify(QObject*, QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18000b599)
    #30 0x7ffd6a39fafc in QCoreApplication::notifyInternal2(QObject*, QEvent*) (E:\build-rpcs3-clang\bin\Qt6Core.dll+0x18008fafc)
    #31 0x7ffd7d85953f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x18000953f)
    #32 0x7ffd7d8c5cf6 in QWidgetWindow::handleMouseEvent(QMouseEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x180075cf6)
    #33 0x7ffd7d8c4e4f in QWidgetWindow::event(QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x180074e4f)
    #34 0x7ffd7d858f6f in QApplicationPrivate::notify_helper(QObject*, QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x180008f6f)
    #35 0x7ffd7d859ea8 in QApplication::notify(QObject*, QEvent*) (E:\build-rpcs3-clang\bin\Qt6Widgets.dll+0x180009ea8)
    #36 0x7ffd6a39fafc in QCoreApplication::notifyInternal2(QObject*, QEvent*) (E:\build-rpcs3-clang\bin\Qt6Core.dll+0x18008fafc)
    #37 0x7ffd7c5f3cbd in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (E:\build-rpcs3-clang\bin\Qt6Gui.dll+0x180083cbd)
    #38 0x7ffd7c65d3d9 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (E:\build-rpcs3-clang\bin\Qt6Gui.dll+0x1800ed3d9)
    #39 0x7ffd6a53c732 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (E:\build-rpcs3-clang\bin\Qt6Core.dll+0x18022c732)    
    #40 0x7ffd7c9794c4 in QWindowsGuiEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (E:\build-rpcs3-clang\bin\Qt6Gui.dll+0x1804094c4)    #41 0x7ffd6a3a9ce5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (E:\build-rpcs3-clang\bin\Qt6Core.dll+0x180099ce5)
    #42 0x7ffd6a3a02a2 in QCoreApplication::exec() (E:\build-rpcs3-clang\bin\Qt6Core.dll+0x1800902a2)
    #43 0x45d36c in qMain(int, char**) C:/src/rpcs3/rpcs3/main.cpp:1390:9
    #44 0x148c847 in main C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexewin.c:67:10
    #45 0x3b1312 in __tmainCRTStartup C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:258:15
    #46 0x3b1155 in .l_startw C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:148:9
    #47 0x7ffdfa657373  (C:\WINDOWS\System32\KERNEL32.DLL+0x180017373)
    #48 0x7ffdfbbdcc90  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18004cc90)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow C:/src/rpcs3/rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:5456:22 in spu_recompiler_base::analyse(stx::se_t<unsigned int, true, 4ull> const*, unsigned int, std::__1::map<unsigned int, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<unsigned int, std::__1::char_traits<unsigned int>, std::__1::allocator<unsigned int>>>>>*)::$_3::operator()() const
Shadow bytes around the buggy address:
  0x12baa6e0ff00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x12baa6e0ff80: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x12baa6e10000: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x12baa6e10080: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x12baa6e10100: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
=>0x12baa6e10180: fc fc fc fc fc fc fc fc fc fc fc fc fc fc[fc]fc
  0x12baa6e10200: fc fc fc fc fc fc fc fc fc fc fc fa fa fa fa fa
  0x12baa6e10280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x12baa6e10300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x12baa6e10380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x12baa6e10400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==5420==ABORTING
```

**Comment by oltolm** [comment]
Probably a false positive.

**Comment by oltolm** [comment]
I have reopened it because it may not be a false positive.

```
(lldb) p reg_state_it.size()
(td::vector<block_reg_state_iterator>::size_type) 0
```
`rchcnt_loop` is a reference to something in the `reg_state_it` vector, but as can see `reg_state_it` is empty at this point in time.

Please take a look.

**Comment by elad335** [comment]
Yep its a typo
