### ISSUE TITLE
Firmware installation gets stucked on Linux

### ISSUE THREAD

**Issue by logos88** [RPCS3/rpcs3#2462]
When I try to install the last firmware downloaded from the playstation website, the blue bar of progression only advances a little and gets stucked there. It doesn't continues. I have tried to download again the firmware but is the same.

- ﻿RPCS3 v0.0.1-4964-48b058386 Pre-Alpha
- System: Archlinux

[RPCS3log.zip](https://github.com/RPCS3/rpcs3/files/817078/RPCS3log.zip)

**Comment by al0xf** [comment]
See if you can get a backtrace with gdb. Also @cornytrace

**Comment by logos88** [comment]
This what gdb gives:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
vm::g_base_addr = 0x7ffde214d000
vm::g_priv_addr = 0x7ffce214d000
[New Thread 0x7ffce09b9700 (LWP 4546)]
[New Thread 0x7ffcdbfff700 (LWP 4547)]
[New Thread 0x7ffcdaf57700 (LWP 4548)]
[New Thread 0x7ffcda756700 (LWP 4549)]
[New Thread 0x7ffcd9f55700 (LWP 4550)]
[New Thread 0x7ffcd9754700 (LWP 4551)]
[Thread 0x7ffcd9754700 (LWP 4551) exited]
[Thread 0x7ffcda756700 (LWP 4549) exited]
[Thread 0x7ffcdaf57700 (LWP 4548) exited]
[New Thread 0x7ffcd9754700 (LWP 4552)]
[Thread 0x7ffcd9754700 (LWP 4552) exited]
[New Thread 0x7ffcd9754700 (LWP 4553)]
[Thread 0x7ffcd9f55700 (LWP 4550) exited]
[New Thread 0x7ffcd9f55700 (LWP 4554)]
[Thread 0x7ffcd9f55700 (LWP 4554) exited]
[Thread 0x7ffcd9754700 (LWP 4553) exited]
[New Thread 0x7ffcd9754700 (LWP 4725)]
[Thread 0x7ffcd9754700 (LWP 4725) exited]
[New Thread 0x7ffcd9f55700 (LWP 5217)]
*** Caught unhandled unknown exception; terminating

Thread 1 "rpcs3" received signal SIGSEGV, Segmentation fault.
0x00007ffff0b46678 in ?? () from /usr/lib/libgobject-2.0.so.0
(gdb) bt full
#0  0x00007ffff0b46678 in  () at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff0b4fbcc in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff0b4ffaf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff1b2fa60 in  () at /usr/lib/libgtk-x11-2.0.so.0
#4  0x00007ffff0b3b648 in g_object_run_dispose ()
    at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff73e5c35 in wxMenu::~wxMenu() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#6  0x00007ffff73e5c89 in wxMenu::~wxMenu() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#7  0x00007ffff7503c57 in wxMenuBarBase::~wxMenuBarBase() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#8  0x00007ffff73e5909 in wxMenuBar::~wxMenuBar() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#9  0x00007ffff7497db6 in wxFrameBase::DeleteAllBars() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#10 0x00007ffff73d82cf in wxFrame::~wxFrame() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#11 0x0000000000a8ba3a in MainFrame::~MainFrame() ()
#12 0x00007ffff741eb76 in wxAppBase::CleanUp() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#13 0x00007ffff6d4055e in wxEntryCleanup() () at /usr/lib/libwx_baseu-3.0.so.0
```

**Comment by hcorion** [comment]
I actually had this problem as well, same OS (Arch Linux) built from scratch using the [rpcs3-git PKGBUILD](https://aur.archlinux.org/packages/rpcs3-git/). I just ignored it and figured it would probably be ironed out.

**Comment by d33tah** [comment]
@logos88 my guess is that we would need backtraces for every running thread
