### ISSUE TITLE
Runtime error on linux (System failure - /rpcs3/rpcs3/Emu/Memory/vm.cpp:329)

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#2493]
terminate called after throwing an instance of 'std::runtime_error'
  what():  **System failure (addr=0xd0114000, size=0x10000)
(in file /home/rui/Programacao/upstream/rpcs3/rpcs3/Emu/Memory/vm.cpp:329**)
[New Thread 0x7ffda2209700 (LWP 17389)]

Thread 27 "rpcs3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffdbcef9700 (LWP 17388)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: Ficheiro ou directoria inexistente.
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
        set = {__val = {0, 140727773266848, 3, 140733193388032, 
            7959393510860551283, 140737264550648, 140727220704800, 
            140727791101199, 140727220701744, 140727422136160, 33890848, 
            140737351941044, 5, 0, 0, 140737254747608}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff21673ea in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, 
          sa_mask = {__val = {140737255221543, 140737258661152, 3432, 1, 
              140737258661283, 140737258641600, 140737255228562, 
              140727773271552, 140737255734509, 1, 140727422205136, 
              140727220701664, 140737258665808, 140727773271808, 
              140737255229803, 140737258661152}}, sa_flags = -226900736, 
          sa_restorer = 0x7ffd9c000c08}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff279f58d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff279d336 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff279d381 in std::terminate() ()

**Comment by rcaridade145** [comment]
This no longer occurs probably due to #2492 so i'm closing this issue
