### ISSUE TITLE
[Linux] SIGSEGV when trying to launch game

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#2551]
I compiled rpcs3 from the latest git using LLVM 3.9 and a Debug build.
These are the cmake flags I used: 
```shell
cmake ../../source/rpcs3 -G "Unix Makefiles" -DUSE_SYSTEM_LIBPNG=ON -DUSE_SYSTEM_FFMPEG=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS='-ldl -lyaml-cpp' -DCMAKE_SKIP_RPATH='ON' -DLLVM_DIR=/usr/
```
This is the SIGSEGV I get when I try to run 1942: Joint Strike Trial:
(debugged using gdb)
```gdb
Thread 10 "rpcs3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffdb77fe700 (LWP 6440)]
0x00007ffff1eae626 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff1eae626 in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00000000016c6196 in rsx::nv0039::buffer_notify(rsx::thread*, unsigned int, unsigned int) (arg=0) at /home/zion/Documents/source/rpcs3/rpcs3/Emu/RSX/rsx_methods.cpp:717
#2  0x0000000001650af0 in rsx::thread::on_task() (this=0x54c2b10) at /home/zion/Documents/source/rpcs3/rpcs3/Emu/RSX/RSXThread.cpp:470
#3  0x00000000018134b7 in named_thread::<lambda()>::operator()(void) const (__closure=0x7ffdb000b320) at /home/zion/Documents/source/rpcs3/Utilities/Thread.cpp:1736
#4  0x00000000018139d4 in task_stack::task_type<named_thread::start_thread(const std::shared_ptr<void>&)::<lambda()> >::invoke(void) (this=0x7ffdb000b310) at /home/zion/Documents/source/rpcs3/rpcs3/../Utilities/Thread.h:46
#5  0x0000000001813b3f in task_stack::invoke() const (this=0x7ffdb77fdb60) at /home/zion/Documents/source/rpcs3/rpcs3/../Utilities/Thread.h:80
#6  0x000000000181272e in thread_ctrl::<lambda(void*)>::operator()(void *) const (__closure=0x0, arg=0x7ffdb000dde0) at /home/zion/Documents/source/rpcs3/Utilities/Thread.cpp:1424
#7  0x0000000001812827 in thread_ctrl::<lambda(void*)>::_FUN(void *) () at /home/zion/Documents/source/rpcs3/Utilities/Thread.cpp:1435
#8  0x00007ffff29dc2e7 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff1e6b54f in clone () at /usr/lib/libc.so.6
```

I set a break point for line 716 and these are the local variables: 
```gdb
(gdb) info locals
i = 0
in_pitch = 512
out_pitch = 320
line_length = 320
line_count = 45
out_format = 1 '\001'
in_format = 1 '\001'
notify = 0
src_offset = 43319296
src_dma = 4276944896
dst_offset = 20971776
dst_dma = 4276944897
dst = 0x7ffe04673100 ""
src = 0x7ffea5ac3000 ""
```
and the locals at the time of the crash: 

```gdb
(gdb) info locals
i = 37
in_pitch = 512
out_pitch = 320
line_length = 320
line_count = 45
out_format = 1 '\001'
in_format = 1 '\001'
notify = 0
src_offset = 43319296
src_dma = 4276944896
dst_offset = 20971776
dst_dma = 4276944897
dst = 0x7ffe04675f40 ""
src = 0x7ffea5ac7a00 ""
```

I'm running Arch Linux 64-bit.

System specs: 
- NVIDIA GTX 1070 with latest binary drivers
- i7 4770 (non-k)
- Dual 1920x1080 screens
- KDE Plasma Window Manager running on X11

The /usr/lib/libc.so.6 mentioned in the SIGSEGV is owned by the package glib, which is version 2.25

Both the interpreter (fast) and recompiler (llvm) were tried. Same error.
SPU Decoder is set to Recompiler (ASMJIT)
No load libraries were pre-defined.
Load required libraries is checked.

Commit hash of build used: 2b79a3691f064362b4ee9fac9c316668fffe1d16

**Comment by hcorion** [comment]
NOTE: I expanded on the original post multiple times after posting, so if you read it as soon as it was posted, more information is available.

**Comment by Nekotekina** [comment]
We use SIGSEGV to invalidate texture cache and other things. You may need to set gdb to ignore it, as said in README.md

**Comment by hcorion** [comment]
Ah, I see. I'm still getting incorrect behaviour (nothing on the screen) Is there any way I can debug this?

**Comment by Nekotekina** [comment]
That's tricky. It may be too slow in debug build. You may try to debug other games if that makes any difference.
