### ISSUE TITLE
Linux/Qt: Crashes on Linux/Qt5

### ISSUE THREAD

**Issue by RomanHargrave** [RPCS3/rpcs3#2949]
At master & 0.0.2 (other tags untested), RPCS3 crashes when starting, as follows:

```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Fatal error: 
Segfault reading location 00007f98e9d7a500 at 00007f98e9d7a500.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
fish: “bin/rpcs3” terminated by signal SIGABRT (Abort)
```

As this is a largely meaningless error, investigation with GDB yields more useful information:

```
(gdb) bt
#0  0x00007fffd8794500 in ?? ()
#1  0x00007ffff73834c9 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#2  0x00007ffff737ddc9 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#3  0x00007ffff7376b6e in glXChooseFBConfig () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#4  0x00007ffff7fec787 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#5  0x00007ffff7fecacd in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#6  0x00007ffff7fe90f9 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#7  0x00007ffff7e57206 in QXcbWindow::create() () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#8  0x00007ffff7e43550 in QXcbIntegration::createPlatformWindow(QWindow*) const () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#9  0x00007ffff25934b9 in QWindowPrivate::create(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007ffff2b5fd85 in QWidgetPrivate::create_sys(unsigned long long, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff2b5f57d in QWidget::create(unsigned long long, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff2b6bb29 in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x0000555556af0913 in rpcs3_app::Init (this=0x7fffffffd720) at /home/roman/Projects/third_party/rpcs3/rpcs3/rpcs3_app.cpp:72
#14 0x0000555556ae287f in main (argc=1, argv=0x7fffffffd8e8) at /home/roman/Projects/third_party/rpcs3/rpcs3/main.cpp:33
```

It appears that something is happening to upset the Qt5 XCB or GlX modules. I'm not quite entirely sure what it is that is causing this behaviour.

Helpful details:

* Using the nVidia proprietary drivers, version 381.22

* GCC 6.3.0

* libqt5gui5 package `5.7.1+dfsg-3+b1`

* Debian Stretch

* Built at dda274af

```
ldd bin/rpcs3                                                                                                                                                           Mon Jul  3 23:29:32 CDT 2017
        linux-vdso.so.1 (0x00007ffc4b375000)
        libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007f7f6442a000)
        libGLEW.so.2.0 => /usr/lib/x86_64-linux-gnu/libGLEW.so.2.0 (0x00007f7f64195000)
        libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f7f63f26000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f7f63be5000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f7f63bc2000)
        libvulkan.so.1 => /usr/lib/x86_64-linux-gnu/libvulkan.so.1 (0x00007f7f63986000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7f63782000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f63565000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7f6334b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7f63143000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f7f62e01000)
        libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f7f62af4000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f7f628c1000)
        libLLVM-4.0.so.1 => /usr/lib/llvm-4.0/lib/libLLVM-4.0.so.1 (0x00007f7f5f8f8000)
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f7f5f295000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f7f5ed5c000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f7f5e88b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7f5e50a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f5e206000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7f5dfef000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f5dc50000)
        /lib64/ld-linux-x86-64.so.2 (0x0000562b39f0d000)
        libsndio.so.6.1 => /usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (0x00007f7f5da40000)
        libnvidia-tls.so.381.22 => /usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.381.22 (0x00007f7f5d83a000)
        libnvidia-glcore.so.381.22 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.381.22 (0x00007f7f5b9ab000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f7f5b799000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f7f5b571000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f7f5b368000)
        libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f7f5b12e000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f7f5af04000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f7f5ac6f000)
        libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007f7f5a7f5000)
        libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f7f5a44d000)
        libpcre16.so.3 => /usr/lib/x86_64-linux-gnu/libpcre16.so.3 (0x00007f7f5a1e4000)
        libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f7f59fd1000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f7f59cbd000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f7f59aa7000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f7f598a3000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f7f5969d000)
        libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f7f59478000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f7f591c9000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f7f58f9c000)
        libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f7f5751f000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f7f572ac000)
```

**Comment by hcorion** [comment]
Extremely weird issue. Are you using X11 or Wayland? My best suggestion would be updating Qt to a newer version.

**Comment by RomanHargrave** [comment]
X11, this should be a rather new Qt, since I'm on the testing branch. 

---- On Mon, 03 Jul 2017 22:55:22 -0700 notifications@github.com wrote ----

Extremely weird issue. Are you using X11 or Wayland? My best suggestion would be updating Qt to a newer version.

**Comment by RomanHargrave** [comment]
This reminds me of an issue feral launcher had with the nVidia GL libraries, wherein it required the GLVND distribution as opposed to the standard GL distribution.

**Comment by hcorion** [comment]
Yeah, debian Qt is still old, Qt is on 5.9.1 now, you're on 5.7. I'm on NVIDIA w/ Binary drivers on Arch Linux and I don't have that problem. If you can get it to build with GLVND, and it turns out that's the solution, then we can provide some cmake flags for using GLVND.

**Comment by RomanHargrave** [comment]
Installing the glvnd packages and removing the non-glvnd packages does in fact appear to remedy the problem for me. It may be worth adding an FAQ item about that, even if the issue is technically with Qt.

**Comment by hcorion** [comment]
@RomanHargrave Can you try to run it on our pre-built AppImages? Download from https://rpcs3.net/download

**Comment by LinAGKar** [comment]
I'm getting similar results on OpenSUSE Leap 42.3 with the AppImage version (proprietary Nvidia driver 384.59, without GLVND):
```> ./rpcs3-v0.0.3-2017-07-29-77f5832-7459_linux64.AppImage 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Fatal error: 
Segfault reading location 00007fa2f8a97510 at 00007fa2f8a97510.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Avbruten (SIGABRT) (minnesutskrift skapad)
```

```(gdb) bt
#0  0x00007fffeaf68510 in ?? ()
#1  0x00007ffff73c64a9 in ?? () from /usr/X11R6/lib64/libGL.so.1
#2  0x00007ffff73c0de9 in ?? () from /usr/X11R6/lib64/libGL.so.1
#3  0x00007ffff73b9b8e in glXChooseFBConfig () from /usr/X11R6/lib64/libGL.so.1
#4  0x00007fffeb41ed07 in ?? () from /tmp/.mount_rpcs3-ZkdiG2/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#5  0x00007fffeb41f02d in ?? () from /tmp/.mount_rpcs3-ZkdiG2/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#6  0x00007fffeb41b350 in ?? () from /tmp/.mount_rpcs3-ZkdiG2/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#7  0x00007fffedaebc59 in QXcbWindow::create() () from /tmp/.mount_rpcs3-ZkdiG2/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#8  0x00007fffedad8ec0 in QXcbIntegration::createPlatformWindow(QWindow*) const () from /tmp/.mount_rpcs3-ZkdiG2/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#9  0x00007ffff4a8bf06 in QWindowPrivate::create(bool, unsigned long long) () from /tmp/.mount_rpcs3-ZkdiG2/usr/bin/../lib/libQt5Gui.so.5
#10 0x00007ffff57b09a7 in QWidgetPrivate::create_sys(unsigned long long, bool, bool) () from /tmp/.mount_rpcs3-ZkdiG2/usr/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff57b0ff9 in QWidget::create(unsigned long long, bool, bool) () from /tmp/.mount_rpcs3-ZkdiG2/usr/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff57bb499 in QWidget::setVisible(bool) () from /tmp/.mount_rpcs3-ZkdiG2/usr/bin/../lib/libQt5Widgets.so.5
#13 0x0000000000d398c8 in rpcs3_app::Init() ()
```
