### ISSUE TITLE
Ni No Kuni Segfault - Linux/OpenGL

### ISSUE THREAD

**Issue by TheCake21** [RPCS3/rpcs3#4105]
Ni No Kuni sometimes randomly segfaults when running using OpenGL on Linux. I haven't yet found a consistent way to reproduce it yet (besides just waiting) but the crash is allways the same. It has not happened when using Vulkan yet.

Backtrace:
```(gdb) bt
#0  0x0000000078000000 in ?? ()
#1  0x0000000000c5843c in GLGSRender::end() ()
#2  0x0000000000d85672 in rsx::nv4097::set_begin_end(rsx::thread*, unsigned int, unsigned int) ()
#3  0x0000000000c91bed in rsx::thread::on_task()::$_2::operator()() const ()
#4  0x0000000000c91299 in rsx::thread::on_task() ()
#5  0x0000000000f2de46 in task_stack::task_type<named_thread::start_thread(std::shared_ptr<void> const&)::$_10>::invoke() ()
#6  0x0000000000f2daec in thread_ctrl::start(std::shared_ptr<thread_ctrl> const&, task_stack)::$_7::__invoke(void*) ()
#7  0x00007f37f38f908c in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007f37efa92e1f in clone () from /usr/lib/libc.so.6
```
Linux 4.9.77-1-MANJARO 
i7-4700HQ
GTX 980M Nvidia Driver 384.111

**Comment by scribam** [comment]
@TheCake21 Is this still happening? Do you have the issue with other games? Do you use the AppImage or did you compile your build?

**Comment by AniLeo** [comment]
Closing for inactivity, reopen if it still happens on master and with a recent nvidia driver branch.
