### ISSUE TITLE
Nitroplus Blasterz [BLJM61299] segfaults

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4120]
As it doesn't load at all, I've decided to provide a backtrace in case someone wishes to take a look at it.
RPCS3 v0.0.4-6358-bb5bdb2e8 Alpha | master

```
(gdb) bt
#0  0x0000000000ac0144 in spu_recompiler_base::enter(SPUThread&) ()
#1  0x00000000008a99ba in cpu_thread::on_task() ()
#2  0x0000000000e75e41 in task_stack::task_type<named_thread::start_thread(std::shared_ptr<void> const&)::{lambda()#1}>::invoke() ()
#3  0x0000000000e78e4b in thread_ctrl::start(std::shared_ptr<thread_ctrl> const&, task_stack)::{lambda(void*)#1}::_FUN(void*) ()
#4  0x00007ffff6d2008c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff2cfce7f in clone () from /usr/lib/libc.so.6
```

**Comment by hcorion** [comment]
Please submit a compatibility report on the forums: https://forums.rpcs3.net/

**Comment by toccata10** [comment]
This is strange: I've got a segfault error messagebox, but the game plays correctly in the background (apart from being greyed (due to the messagebox), it seems to be very correct). Of course, if I click on "OK" in the fatal error message box, it closes everything.

![selection_018](https://user-images.githubusercontent.com/7478580/35590455-3a9656dc-0607-11e8-991e-b8f21586b00e.jpg)

**Comment by toccata10** [comment]
With the log file
[RPCS3.log-Nitro2.zip](https://github.com/RPCS3/rpcs3/files/1680906/RPCS3.log-Nitro2.zip)

**Comment by scribam** [comment]
@toccata10 Is it still an issue? The last comment on this thread https://forums.rpcs3.net/thread-178769.html doesn't mention the segfault.
