### ISSUE TITLE
sky force anniversary [NPUB31813] segfaults when accessing cards

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4443]
On PPU interpreter (game doesn't start with llvm), it segfaults when I try to acces a display the cards.
On the console:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556590), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556590), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556590), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556590), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556590), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556cb0), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Breeze::WidgetStateEngine(0x5556cb0), parent's thread is QThread(0x54d32d0), current thread is QThread(0x7fcc68000d30)
QTextLine: Can't set a line width while not layouting.
QPaintDevice: Cannot destroy paint device that is being painted
QWidget::repaint: Recursive repaint detected
Processus arrêté
```
With gdb and a backtrace: the game doesn't go very far. It stops with:
```
#0  0x00000000009e00d2 in ppu_interpreter::LD(ppu_thread&, ppu_opcode_t) ()
#1  0x00000000009f26e4 in ppu_thread::exec_task() ()
#2  0x00000000009f2f3e in ppu_thread::fast_call(unsigned int, unsigned int) ()
#3  0x00000000009f97a6 in ppu_thread::cpu_task() ()
#4  0x00000000008244ca in cpu_thread::on_task() ()
#5  0x0000000000da7761 in task_stack::task_type<named_thread::start_thread(std::shared_ptr<void> const&)::{lambda()#1}>::invoke() ()
#6  0x0000000000daa89b in thread_ctrl::start(std::shared_ptr<thread_ctrl> const&, task_stack)::{lambda(void*)#1}::_FUN(void*) ()
#7  0x00007ffff63ab08c in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007ffff204ee7f in clone () from /usr/lib/libc.so.6
```
The logfile
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1910553/RPCS3.zip)
and my save (I think I managed to get 2 cards):
[NPUB31813-SAVEDATA0.zip](https://github.com/RPCS3/rpcs3/files/1910567/NPUB31813-SAVEDATA0.zip)
I tried to not use the "native user interface" but it stops very during the "loading shaders".

**Comment by toccata10** [comment]
problem solved on rev8143
