### ISSUE TITLE
Segfault reading location error on Linux - KIngdom Hearts games

### ISSUE THREAD

**Issue by MojoJojoDojo** [RPCS3/rpcs3#4849]
My PC Specs:
CPU: Intel i7 8550U
RAM:  8 GB
GPU ; Radeon 530
OS : Manjaro Linux 17.1.11
RPCS3 Version : 0.0.5-7022
I get the following error every time i try to launch one of the 3 games in any of the compilations:
![2018-07-05 22-20-16](https://user-images.githubusercontent.com/33392696/42335288-8d087e58-8088-11e8-9c2d-8c0794a2371d.png).
I load my games from my NTFS drive as I dont have enough space on Linux.
The games load on WIndows without any errors.

**Comment by AniLeo** [comment]
Invalid issue, specially since hcorion fixed a related bug in 7023.

Retest and, if issue persists, you need to provide a stack trace. Segfault itself doesn't tell much.

**Comment by hcorion** [comment]
Yes, upload backtrace please, are you using X11 or Wayland?

**Comment by MojoJojoDojo** [comment]
Even in the latest i get the same error.
I dont know how to do a stack trace or backtrace.
Here is the log i get : 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2169359/RPCS3.log)

**Comment by hcorion** [comment]
It's probably because you're trying with SPU LLVM, have you tried setting `SPU Decoder` to `ASMJIT Recompiler (fastest)`

**Comment by hcorion** [comment]
Also, to get a stacktrace run
```
gdb ./rpcs3-v0.0.5-7069-d856dc89_linux64.appimage
```
then when the segfault happens, go back to the terminal, type
`bt` and then hit enter and copy the output that follows and paste it here.

**Comment by MojoJojoDojo** [comment]
I cant use the appimage without extracting it first.
Is there another way?
can i use gdb with the the extracted executable?

**Comment by hcorion** [comment]
yes, use gdb with the extracted executable.
Why do you need to run rpcs3 extracted? Just install FUSE, that should be it.

**Comment by MojoJojoDojo** [comment]
I get this when i try to use gdb 

> Reading symbols from ./rpcs3-v0.0.5-7069-d856dc89_linux64.AppImage...(no debugging symbols found)...done.

**Comment by MojoJojoDojo** [comment]
OK sorted it out.
This is what i get : 
``#0  0x0000000000ed2907 in thread_ctrl::notify() ()
#1  0x0000000000b0a119 in lv2_obj::schedule_all() ()
#2  0x0000000000b0a9ac in lv2_obj::awake(cpu_thread&, unsigned int) ()
#3  0x0000000000b41af2 in _sys_ppu_thread_exit(ppu_thread&, unsigned long) ()
#4  0x0000000000b0b185 in $_15::__invoke(ppu_thread&) ()
#5  0x0000000000a4045f in ppu_thread::fast_call(unsigned int, unsigned int) ()
#6  0x0000000000a3f9e5 in ppu_thread::cpu_task() ()
#7  0x00000000008499a3 in cpu_thread::on_task() ()
#8  0x0000000000ed39c6 in task_stack::task_type<named_thread::start_thread(std::shared_ptr<void> const&)::$_10>::invoke() ()
#9  0x0000000000ed3619 in thread_ctrl::start(std::shared_ptr<thread_ctrl> const&, task_stack)::$_7::__invoke(void*) ()
#10 0x00007ffff79be075 in start_thread () from /usr/lib/libpthread.so.0
#11 0x00007ffff2cf953f in clone () from /usr/lib/libc.so.6

**Comment by hcorion** [comment]
This doesn't seem like an issue with the AppImages.
Do you have any games other than Kingdom Hearts? If not, could you try ScoggerHD? You can get it here: http://store.brewology.com/ahomebrew.php?brewid=170

**Comment by MojoJojoDojo** [comment]
I think it only happens with game collections (game within a game).

**Comment by kd-11** [comment]
Closing due to inactivity.
