### ISSUE TITLE
ps3 firmware installation issue

### ISSUE THREAD

**Issue by xelmasx** [RPCS3/rpcs3#5308]
Log attached.
[rpcs3-20181105-011402.kcrash.txt](https://github.com/RPCS3/rpcs3/files/2546370/rpcs3-20181105-011402.kcrash.txt)

**Comment by hcorion** [comment]
Are you using self-compiled or AppImage? What distro, Qt version, X11 or wayland, window manager/DE?

**Comment by xelmasx** [comment]
I use Archlinux + KDE plasma (Wayland) and Appimage.  Spec ; CPU : amd 2700x , GPU  : amd Vega 56 .

**Comment by hcorion** [comment]
that's a strange backtrace if you're using an AppImage, it shouldn't be using the system's qt5.
You're just downloading and running the AppImage? nothing fancy?

**Comment by AnonJump** [comment]
I have this problem too. 
When I try to upgrade to version 4.83 from 4.82, the process of installing the update hangs at 4%. Then rpcs3.exe crashed. 
![default](https://user-images.githubusercontent.com/12502605/48021881-1d9a8080-e153-11e8-9915-fe042baa6c88.png)

**Comment by AniLeo** [comment]
When did Appimages start working on Windows 10? Are you using the Linux Subsystem?

**Comment by xelmasx** [comment]
I dont know how much it is going to help you but I get such error in kconsole;

QObject::setParent: Cannot set parent, new parent is in a different thread
QBasicTimer::start: Timers cannot be started from another thread
QBasicTimer::start: Timers cannot be started from another thread

**Comment by xelmasx** [comment]
> that's a strange backtrace if you're using an AppImage, it shouldn't be using the system's qt5.
> You're just downloading and running the AppImage? nothing fancy?

The log I attached it belongs to KDE plasma not rpcs3. Rpcs3 gives this error -->
![screenshot_20181105_234813](https://user-images.githubusercontent.com/21128451/48025953-cd70ed80-e155-11e8-8c43-fa1613008f9a.jpeg)

**Comment by AnonJump** [comment]
>Are you using the Linux Subsystem for W10?
No. I downloaded RPCS3 from https://rpcs3.net/download , "for Windows" version.

**Comment by AniLeo** [comment]
Then you're not using the AppImage since it's Linux exclusive and it can be a different issue

**Comment by hcorion** [comment]
Can you provide a backtrace @xelmasx ?
to do so run rpcs3 via gdb as follows:
1. Run the following in your terminal: `gdb ./path/to/rpcs3.AppImage`
2. and then once the gdb prompt shows up (should look like `(gdb)`)
type `run`
3. Now rpcs3 will launch normally, now try to reproduce the crash by installing the firmware.
4. Once rpcs3 has frozen due to the crash, go back to terminal (don't force close rpcs3).
5. Now type `bt` into the gdb prompt and copy and paste the resulting output.

**Comment by xelmasx** [comment]
> Can you provide a backtrace @xelmasx ?
> to do so run rpcs3 via gdb as follows:
> 
>     1. Run the following in your terminal: `gdb ./path/to/rpcs3.AppImage`
> 
>     2. and then once the gdb prompt shows up (should look like `(gdb)`)
>        type `run`
> 
>     3. Now rpcs3 will launch normally, now try to reproduce the crash by installing the firmware.
> 
>     4. Once rpcs3 has frozen due to the crash, go back to terminal (don't force close rpcs3).
> 
>     5. Now type `bt` into the gdb prompt and copy and paste the resulting output.

Here is gdb error output --->

Thread 28 "Firmware Instal" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8dffb700 (LWP 6096)]
0x0000000000c3987f in tar_object::tar_object(fs::file const&, unsigned long) ()
(gdb) bt
#0  0x0000000000c3987f in tar_object::tar_object(fs::file const&, unsigned long) ()
#1  0x0000000000b61b20 in named_thread<main_window::InstallPup(QString const&)::$_1>::entry_point(void*) ()
#2  0x00007ffff6a75a9d in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff460eb23 in clone () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000000000c3987f in tar_object::tar_object(fs::file const&, unsigned long) ()
#1  0x0000000000b61b20 in named_thread<main_window::InstallPup(QString const&)::$_1>::entry_point(void*) ()
#2  0x00007ffff6a75a9d in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff460eb23 in clone () from /usr/lib/libc.so.6

**Comment by kd-11** [comment]
Closing due to inactivity.
