### ISSUE TITLE
Dead or alive 5: last round [NPEB02203] crashes the system (Linux)

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#5828]
ArchLinux, R9 fury.
Soon after selecting characters, this game freezes the computer (hard reboot necessary).
So I backtraced this morning with
gdb ./rpcs3-v0.0.6-7967-8da78c09_linux64.AppImage 
```
swscaler @ 0x7ffd7c0e20c0] No accelerated colorspace conversion found from yuva420p to argb.

Thread 215 "PPU[0x1000033] " received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe5cff9700 (LWP 7681)]
0x0000000001d7fae9 in yuva2argb_c (c=0x7ffd7c0e20c0, src=<optimized out>, srcStride=0x7ffe5cff8950, srcSliceY=0, srcSliceH=720, dst=<optimized out>, dstStride=0x7ffe5cff8960)
    at libswscale/yuv2rgb.c:303
303     libswscale/yuv2rgb.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  0x0000000001d7fae9 in yuva2argb_c (c=0x7ffd7c0e20c0, src=<optimized out>, srcStride=0x7ffe5cff8950, srcSliceY=0, srcSliceH=720, dst=<optimized out>, dstStride=0x7ffe5cff8960)
    at libswscale/yuv2rgb.c:303
#1  0x0000000001d71fcb in sws_scale (c=<optimized out>, srcSlice=<optimized out>, srcStride=<optimized out>, srcSliceY=0, srcSliceH=720, dst=<optimized out>, dstStride=0x7ffe5cff8a50)
    at libswscale/swscale.c:1276
#2  0x0000000000a98cda in cellVdecGetPicture(unsigned int, vm::_ptr_base<CellVdecPicFormat const, unsigned int>, vm::_ptr_base<unsigned char, unsigned int>) ()
#3  0x0000000000a99080 in cellVdecGetPictureExt(unsigned int, vm::_ptr_base<CellVdecPicFormat2 const, unsigned int>, vm::_ptr_base<unsigned char, unsigned int>, unsigned int) ()
#4  0x0000000000a9a3aa in ppu_module_manager::$_0::operator()() const::{lambda(ppu_thread&)#13}::__invoke ()
#5  0x00000000007691df in ppu_thread::fast_call(unsigned int, unsigned int) ()
#6  0x00000000007686f8 in ppu_thread::cpu_task() ()
#7  0x000000000086704a in cpu_thread::operator()() ()
#8  0x0000000000766029 in named_thread<ppu_thread>::entry_point(void*) ()
#9  0x00007ffff6a52a9d in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007ffff47edb23 in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by elad335** [comment]
Does this happen with windows as well? could be an issue with ffmpeg if not.

**Comment by toccata10** [comment]
A bit more testing:
On Linux, R9 fury, vulkan: exploding vertices, freezes computer a few moments after entering an arena
On linux, I tried with Ogl: the game stops quickly with:
```
S {PPU[0x100002c] Thread (MTC : 1) [0x027709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
U {PPU[0x100002c] Thread (MTC : 1) [0x027402b0]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x1386ed0, arg=*0x0, hid=*0x300b7d98)
U {PPU[0x100002c] Thread (MTC : 1) [0x02745940]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
F {RSX [0x01d4548]} RSX: N3gsl9fail_fastE thrown: GSL: Precondition failure at ../3rdparty/GSL/include/gsl/span: 621
```
Same Hardware, Win10, Vulkan: game works fine (a few glitches). Seems playable (10min testing).
On a latop with nvidia gpu, Vulkan works fine (a few glitches). Seems playable (10min testing).

**Comment by toccata10** [comment]
rev8365, mesa 19.1, Ogl (Radv gives a black screen due to llvm 8 bug): the game is playable with resolution 100%.
(Upscaling to 4k can bring it to a crawl and there are some color issues #6200)
