### ISSUE TITLE
Killzone 2 Linux Segfault

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#6929]
(gdb) bt full
#0  0x0000000042cad0b6 in ?? ()
No symbol table info available.
#1  0x0000000500000000 in ?? ()
No symbol table info available.
#2  0x00007ffe9cacc8f0 in ?? ()
No symbol table info available.
#3  0x00000000006d82ff in ppu_thread::exec_task() ()
No symbol table info available.
#4  0x00000000006d7e9f in ppu_thread::fast_call(unsigned int, unsigned int) ()
No symbol table info available.
#5  0x00000000006d7528 in ppu_thread::cpu_task() ()
No symbol table info available.
#6  0x000000000094660c in cpu_thread::operator()() ()
No symbol table info available.
#7  0x00000000006d504e in named_thread<ppu_thread>::entry_point(void*) ()
No symbol table info available.
#8  0x00007ffff7528669 in start_thread (arg=<optimized out>)
    at pthread_create.c:479
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140729485612800, 
                -3344534590639280795, 140733797361374, 140733797361375, 
                140733797361376, 140729485609856, 3344369662391512421, 
--Type <RET> for more, q to quit, c to continue without paging--
                3234193765}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#9  0x00007ffff5346323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) 

Version  - rpcs3-v0.0.7-9053-03a2d36c_linux64.AppImage
Write Color Buffers On
Multithreaded RSX On
Vulkan
SPU Block Safe 
Accurate xfloat - off

**Comment by rcaridade145** [comment]
Tried it last nigt and it was all ok .
