### ISSUE TITLE
Segmentation fault when starting a game with --no-gui

### ISSUE THREAD

**Issue by raelgc** [RPCS3/rpcs3#7015]
## Description
I'm getting a segmentation fault when I start a game using the `--no-gui` option. Same game runs fine without this option.

## Commit Hash
https://github.com/RPCS3/rpcs3/commit/cd6b6c8a4f19595ac339efbf86602ecf59b5a497

## System Info
Ubuntu 18.04 amd64
RPCS3 Firmware version: 4.85
Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz | 8 Threads | 15.57 GiB RAM | TSC: Bad | AVX+

## Steps to reproduce
1. Open a terminal
2. Started Skate3 game with `--no-gui` option: `./rpcs3.AppImage --no-gui /home/rael/games/ps3/Skate3.PS3/PS3_GAME/USRDIR/EBOOT.BIN`
3. Wait the Build SPU cache dialog finish.

**Expected Results**: Build SPU cache dialog finished, game will start.
**Current Results**: Segmentation fault after rpcs3 finished the Build SPU cache. 

## Backtrace

```gdb ./rpcs3.AppImage 

GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./rpcs3.AppImage...(no debugging symbols found)...done.

(gdb) r --no-gui /home/rael/games/ps3/Skate3.PS3/PS3_GAME/USRDIR/EBOOT.BIN

Starting program: /home/rael/rpcs3.AppImage --no-gui /home/rael/games/ps3/Skate3.PS3/PS3_GAME/USRDIR/EBOOT.BIN
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 9116 is executing new program: /tmp/.mount_rpcs3.bDzIcM/AppRun
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 9116 is executing new program: /tmp/.mount_rpcs3.bDzIcM/usr/bin/rpcs3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff6b20d700 (LWP 9145)]
[New Thread 0x7fff67288700 (LWP 9163)]
[New Thread 0x7fff6666d700 (LWP 9165)]
Xlib:  extension "NV-GLX" missing on display ":0".
INTEL-MESA: warning: Haswell Vulkan support is incomplete
[New Thread 0x7fff557df700 (LWP 9169)]
[Thread 0x7fff557df700 (LWP 9169) exited]
[Thread 0x7fff6666d700 (LWP 9165) exited]
[New Thread 0x7fff6666d700 (LWP 9177)]
[Thread 0x7fff6666d700 (LWP 9177) exited]
[New Thread 0x7fff6666d700 (LWP 9188)]
[Thread 0x7fff6666d700 (LWP 9188) exited]
[New Thread 0x7fff6666d700 (LWP 9189)]
[New Thread 0x7fff557df700 (LWP 9197)]
[New Thread 0x7fff65664700 (LWP 9198)]
[New Thread 0x7fff566fe700 (LWP 9199)]
[New Thread 0x7fff54fde700 (LWP 9201)]
[New Thread 0x7fff4d22d700 (LWP 9203)]
[New Thread 0x7fff4ca2c700 (LWP 9204)]
[New Thread 0x7fff47fff700 (LWP 9205)]
[New Thread 0x7fff3f7fe700 (LWP 9206)]
[New Thread 0x7fff477fe700 (LWP 9207)]
[New Thread 0x7fff46ffd700 (LWP 9208)]
[New Thread 0x7fff467fc700 (LWP 9209)]
[New Thread 0x7fff45ffb700 (LWP 9210)]
[New Thread 0x7fff457fa700 (LWP 9216)]
[New Thread 0x7fff44ff9700 (LWP 9218)]
[New Thread 0x7fff3ffff700 (LWP 9219)]
[New Thread 0x7fff3effd700 (LWP 9220)]
[New Thread 0x7fff4ffff700 (LWP 9246)]
[New Thread 0x7fff4f7fe700 (LWP 9247)]
[New Thread 0x7fff4effd700 (LWP 9248)]
[New Thread 0x7fff4e7fc700 (LWP 9249)]
[New Thread 0x7fff4dffb700 (LWP 9250)]
[New Thread 0x7fff3e7fc700 (LWP 9251)]
[New Thread 0x7fff3dffb700 (LWP 9252)]
[New Thread 0x7fff3d7fa700 (LWP 9253)]
[New Thread 0x7fff33df5700 (LWP 9255)]
[Thread 0x7fff4dffb700 (LWP 9250) exited]
[Thread 0x7fff4f7fe700 (LWP 9247) exited]
[Thread 0x7fff4ffff700 (LWP 9246) exited]
[Thread 0x7fff3d7fa700 (LWP 9253) exited]
[Thread 0x7fff4effd700 (LWP 9248) exited]
[Thread 0x7fff4e7fc700 (LWP 9249) exited]
[Thread 0x7fff3dffb700 (LWP 9252) exited]
[Thread 0x7fff3e7fc700 (LWP 9251) exited]
[Thread 0x7fff557df700 (LWP 9197) exited]
[Thread 0x7fff67288700 (LWP 9163) exited]
[Thread 0x7fff33df5700 (LWP 9255) exited]
[Thread 0x7fff44ff9700 (LWP 9218) exited]
[Thread 0x7fff6b20d700 (LWP 9145) exited]

Thread 10 "PPU[0x1000000] " received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff65664700 (LWP 9198)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:356
356	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.

(gdb) backtrace full

#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:356
No locals.
#1  0x0000000000672364 in logs::file_listener::log(unsigned long, logs::message const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
No symbol table info available.
#2  0x000000000066ef63 in logs::message::broadcast(char const*, fmt_type_info const*, ...) const ()
No symbol table info available.
#3  0x000000000067d42d in thread_base::finalize(int) ()
No symbol table info available.
#4  0x00000000006d7178 in named_thread<ppu_thread>::entry_point(void*) ()
No symbol table info available.
#5  0x00007ffff5c0c6db in start_thread (arg=0x7fff65664700) at pthread_create.c:463
        pd = 0x7fff65664700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140734894589696, -9154876051204071113, 140734894586752, 
                0, 94301600, 140737488337648, 9155134627663323447, 9154889220870119735}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007ffff320388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by dio-gh** [comment]
Known issue, it's because of the no-gui (and headless?) options being unfinished.

**Comment by Megamouse** [comment]
Please try again.
Keep in mind that no-gui hides everything that is not the game window, so you won't see compilation dialogs anymore (until someone changes the game window to be detached from boot logic)

**Comment by raelgc** [comment]
Thank you! It works! I was trying to [add RCPS3 to Retropie](https://github.com/RetroPie/RetroPie-Setup/pull/2905/files) (for PC).
